//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments
    {
        public int Assignment_Confirmation_No { get; set; }
        public int Registration_No { get; set; }
        public string Client_Name { get; set; }
        public string Position { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Rating { get; set; }
        public string End_Condition { get; set; }
    }
}
