//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crim_Check
    {
        public int Crim_Number { get; set; }
        public int Registration_No { get; set; }
        public string Criminal_Result { get; set; }
        public Nullable<System.DateTime> Criminal_Date { get; set; }
    }
}
