//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplinary
    {
        public int Disciplinary_No { get; set; }
        public int Registration_No { get; set; }
        public string Chairperson { get; set; }
        public string Charge { get; set; }
        public System.DateTime Date_of_Disciplinary { get; set; }
        public string Plea { get; set; }
        public string Sanction { get; set; }
        public string Reason_for_Sanction { get; set; }
        public Nullable<System.DateTime> Expiry_Date_for_Sanction { get; set; }
        public string Additional_Comment { get; set; }
        public string Employee_Number { get; set; }
    }
}
