//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers_Reference
    {
        public int Reference_No { get; set; }
        public int Registration_No { get; set; }
        public string ID_or_Passport { get; set; }
        public string Company_Name { get; set; }
        public string Physical_Address { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public string Dates_of_Employment { get; set; }
        public string Reason_for_Leaving { get; set; }
        public string Responsibilities { get; set; }
        public string Formal_Training { get; set; }
        public string FT_Comment { get; set; }
        public string Pull_Trailer { get; set; }
        public string Tow_Vehicles { get; set; }
        public string Experience_Driving { get; set; }
        public string Drivers_Log { get; set; }
        public string Accurate_Submission { get; set; }
        public string Stock_Shortages { get; set; }
        public string SS_Comment { get; set; }
        public string Cash_Responsibility { get; set; }
        public string CR_Comment { get; set; }
        public string Punctuality { get; set; }
        public string Communication_Skills { get; set; }
        public string Interaction_with_Others { get; set; }
        public string Strengths_and_Weaknesses { get; set; }
        public string Problem_Solving { get; set; }
        public string Willing_to_Re_Employ { get; set; }
        public string WRE_Comment { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
