//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Education_No { get; set; }
        public int Registration_No { get; set; }
        public string Qualification { get; set; }
        public string Category { get; set; }
    }
}
