//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Positions
    {
        public int Position_No { get; set; }
        public int Register_No { get; set; }
        public string Position { get; set; }
        public string Experience { get; set; }
    }
}
