//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Detail
    {
        public int Registration_No { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Home_Language { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public string Nature_of_Disability { get; set; }
        public string Martial_Status { get; set; }
        public string Health { get; set; }
        public string Vaccinated { get; set; }
        public string NoK_Name { get; set; }
        public string NoK_Contact { get; set; }
        public string NoK_Relationship { get; set; }
        public string Own_Transport { get; set; }
        public Nullable<bool> Accident_History { get; set; }
        public string Accident_Detail { get; set; }
    }
}
