//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qrMasterEntities : DbContext
    {
        public qrMasterEntities()
            : base("name=qrMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Register_Form> Register_Form { get; set; }
        public virtual DbSet<RecruitmentTable> RecruitmentTable { get; set; }
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<Disciplinary> Disciplinary { get; set; }
        public virtual DbSet<Licence> Licence { get; set; }
        public virtual DbSet<Employee_Detail> Employee_Detail { get; set; }
        public virtual DbSet<Employee_Positions> Employee_Positions { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Drivers_Reference> Drivers_Reference { get; set; }
        public virtual DbSet<Track_Modifications> Track_Modifications { get; set; }
        public virtual DbSet<Location_Area> Location_Area { get; set; }
        public virtual DbSet<Standard_Reference> Standard_Reference { get; set; }
        public virtual DbSet<Crim_Check> Crim_Check { get; set; }
    }
}
