//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licence
    {
        public int Licence_No { get; set; }
        public int Registration_No { get; set; }
        public string Licence_Type { get; set; }
        public string Licence_Code { get; set; }
        public System.DateTime Licence_Expiry_Date { get; set; }
        public string MHV_Attachment { get; set; }
    }
}
