//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitmentTable
    {
        public int Reg_No { get; set; }
        public string Employee_Number { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ID { get; set; }
        public string Passport { get; set; }
        public string Tel_1 { get; set; }
        public string Tel_2 { get; set; }
        public string Home_Address { get; set; }
        public string Area { get; set; }
        public string Race { get; set; }
        public string Gender { get; set; }
        public string Positions { get; set; }
        public string Initial_Impression { get; set; }
        public Nullable<int> ABET_Num { get; set; }
        public Nullable<int> ABET_Lit { get; set; }
        public Nullable<int> Interview { get; set; }
        public Nullable<int> Reference_1 { get; set; }
        public Nullable<int> Reference_2 { get; set; }
        public string Crime_Check { get; set; }
        public Nullable<bool> Master_Contract { get; set; }
        public string Manager_Approval { get; set; }
        public string Employment_Status { get; set; }
        public string Audit_By { get; set; }
        public string Vetted_By { get; set; }
        public string Tax_Number { get; set; }
        public Nullable<System.DateTime> Last_Modified { get; set; }
        public string Decline_Reason { get; set; }
        public string Interview_Type { get; set; }
        public string Reference_Type_1 { get; set; }
        public string Reference_Type_2 { get; set; }
        public string Work_Permit { get; set; }
        public System.DateTime Date_Added { get; set; }
        public Nullable<bool> Vetting_Finished { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
    }
}
