//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_Form
    {
        public string Employee_ID { get; set; }
        public string Site_ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time_In { get; set; }
        public Nullable<System.TimeSpan> Time_Out { get; set; }
        public string Location_In { get; set; }
        public decimal Distance_to_Site_Location { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    }
}
