//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard_Reference
    {
        public int Reference_No { get; set; }
        public int Registration_No { get; set; }
        public string Obtained_From { get; set; }
        public string Position { get; set; }
        public string Company_Name { get; set; }
        public string Physical_Address { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Confirmation_of_Info { get; set; }
        public string Presentation_Skills { get; set; }
        public string PS_Comment { get; set; }
        public string Decision_Making_Ability { get; set; }
        public string DMA_Comment { get; set; }
        public string Quality_of_Work { get; set; }
        public string QoW_Comment { get; set; }
        public string Organisation_Skills { get; set; }
        public string OS_Comment { get; set; }
        public string Flexibility { get; set; }
        public string Flexibility_Comment { get; set; }
        public string Working_Speed { get; set; }
        public string WS_Comment { get; set; }
        public string Attitude { get; set; }
        public string Attitude_Comment { get; set; }
        public string Reliability { get; set; }
        public string Reliability_Comment { get; set; }
        public string Dependability { get; set; }
        public string Dependability_Comment { get; set; }
        public string Relationships_with_Others { get; set; }
        public string RO_Comment { get; set; }
        public string Initiative { get; set; }
        public string Initiative_Comment { get; set; }
        public string Trustworthy { get; set; }
        public string Trustworthy_Comment { get; set; }
        public string Any_Problems_Experienced { get; set; }
        public string APE_Comment { get; set; }
        public string Recommendation_to_Position { get; set; }
        public string RP_Comment { get; set; }
        public string Willing_to_Re_Employ { get; set; }
        public string Reason_for_Recommendation { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
