//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASAQR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_Modifications
    {
        public int Track_No { get; set; }
        public int ID { get; set; }
        public string Modified_Table { get; set; }
        public Nullable<int> Modified_Registration_No { get; set; }
        public string Modified_Action { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
